let
    Origen = Folder.Files("C:\Users\cacutagu\Desktop\ExtraerTextoResultado"),
    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo", each #"Transformar archivo"([Content])),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo"}),
    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo", Table.ColumnNames(#"Transformar archivo"(#"Archivo de ejemplo"))),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"Column1", type text}}),
    #"Dividir columna por: transición de caracteres" = Table.SplitColumn(#"Tipo cambiado", "Source.Name", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({"0".."9"}, c), {"0".."9"}), {"Source.Name.1", "Source.Name.2", "Source.Name.3"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Dividir columna por: transición de caracteres",{"Source.Name.1", "Source.Name.3"}),
    #"Dividir columna por: transición de caracteres1" = Table.SplitColumn(#"Columnas quitadas", "Source.Name.2", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Source.Name.2.1", "Source.Name.2.2"}),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Dividir columna por: transición de caracteres1",{"Source.Name.2.2"}),
    Source_Name = Table.RenameColumns(#"Columnas quitadas1",{{"Source.Name.2.1", "Source.Name"}}),
    #"Valor reemplazado" = Table.ReplaceValue(Source_Name,"{""Texto"":""M""},","",Replacer.ReplaceText,{"Column1"}),
    #"Valor reemplazado13" = Table.ReplaceValue(#"Valor reemplazado","{""Texto"":""CUN/SN:""},{""Texto"":""",",{""Texto"":""CUN/SN",Replacer.ReplaceText,{"Column1"}),
    #"Valor reemplazado14" = Table.ReplaceValue(#"Valor reemplazado13","{""Texto"":""CUN""},{""Texto"":""",",{""Texto"":""CUN/SN",Replacer.ReplaceText,{"Column1"}),
    #"Valor reemplazado15" = Table.ReplaceValue(#"Valor reemplazado14","{""Texto"":""SN""},{""Texto"":""",",{""Texto"":""CUN/SN",Replacer.ReplaceText,{"Column1"}),
    #"Valor reemplazado16" = Table.ReplaceValue(#"Valor reemplazado15","{""Texto"":""CUN:""},{""Texto"":""",",{""Texto"":""CUN/SN",Replacer.ReplaceText,{"Column1"}),
    #"Valor reemplazado17" = Table.ReplaceValue(#"Valor reemplazado16","{""Texto"":""SN:""},{""Texto"":""",",{""Texto"":""CUN/SN",Replacer.ReplaceText,{"Column1"}),
    /*------Inicia Aislar fecha de la carta------*/
    Fecha = Table.AddColumn(#"Valor reemplazado17", "Fecha", each Text.BeforeDelimiter([Column1],"}")),
    #"Texto recortado" = Table.TransformColumns(Fecha,{{"Fecha", Text.Trim, type text}}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Texto recortado"," D.C","",Replacer.ReplaceText,{"Fecha"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","[{""Texto"":""Bogotá,","",Replacer.ReplaceText,{"Fecha"}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado2","[{""Texto"":""Bogotá ","",Replacer.ReplaceText,{"Fecha"}),
    #"Texto recortado1" = Table.TransformColumns(#"Valor reemplazado7",{{"Fecha", Text.Trim, type text}}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Texto recortado1","""","",Replacer.ReplaceText,{"Fecha"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3",".","",Replacer.ReplaceText,{"Fecha"}),
    #"Texto en minúsculas" = Table.TransformColumns(#"Valor reemplazado4",{{"Fecha", Text.Lower, type text}}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Texto en minúsculas","de","",Replacer.ReplaceText,{"Fecha"}),
    #"Texto recortado2" = Table.TransformColumns(#"Valor reemplazado5",{{"Fecha", Text.Trim, type text}}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Texto recortado2"," l "," ",Replacer.ReplaceText,{"Fecha"}),
    TipoFecha = Table.TransformColumnTypes(#"Valor reemplazado6",{{"Fecha", type date}}),
    /*------Extraccion de CUN------*/
    ExtraccionCUN = Table.AddColumn(TipoFecha, "ExtraccionCUN", each if Text.Contains([Column1],"{""Texto"":""CUN/SN") then Text.AfterDelimiter([Column1],"{""Texto"":""CUN/SN") else if Text.Contains([Column1],"{""Texto"":""CUN") then Text.AfterDelimiter([Column1],"{""Texto"":""CUN") else if Text.Contains([Column1],"{""Texto"":""SN") then Text.AfterDelimiter([Column1],"{""Texto"":""SN") else null),
    #"Valor reemplazado8" = Table.ReplaceValue(ExtraccionCUN,":","",Replacer.ReplaceText,{"ExtraccionCUN"}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","–","",Replacer.ReplaceText,{"ExtraccionCUN"}),
    #"Texto recortado3" = Table.TransformColumns(#"Valor reemplazado9",{{"ExtraccionCUN", Text.Trim, type text}}),
    CUN = Table.AddColumn(#"Texto recortado3", "CUN/SN", each Text.BeforeDelimiter([ExtraccionCUN],"""},{""")),
    EliminarExtraccionCUN = Table.RemoveColumns(CUN,{"ExtraccionCUN"}),
    #"Valor reemplazado10" = Table.ReplaceValue(EliminarExtraccionCUN,".","",Replacer.ReplaceText,{"CUN/SN"}),
    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","/SN","",Replacer.ReplaceText,{"CUN/SN"}),
    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","- SN ","",Replacer.ReplaceText,{"CUN/SN"}),
    #"Texto recortado4" = Table.TransformColumns(#"Valor reemplazado12",{{"CUN/SN", Text.Trim, type text}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Texto recortado4",{{"Column1", "TextoCarta"}}),
    /*------Ordenamos las columnas------*/
    OrdenColumnas = Table.ReorderColumns(#"Columnas con nombre cambiado",{"Source.Name", "Fecha", "CUN/SN", "TextoCarta"}),
    /*------Se compara cun nom file vs cun carta------*/
    CompararCUN = Table.AddColumn(OrdenColumnas, "CUN_Vs_CUNFile", each if [#"CUN/SN"] = [Source.Name] then 1 else 0),
    #"Columnas reordenadas" = Table.ReorderColumns(CompararCUN,{"Source.Name", "Fecha", "CUN/SN", "CUN_Vs_CUNFile", "TextoCarta"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas reordenadas",{{"CUN_Vs_CUNFile", Int64.Type}}),
    TextoCartaClean = Table.DuplicateColumn(#"Tipo cambiado1", "TextoCarta", "TextoCarta - Copia"),
    #"Columnas con nombre cambiado2" = Table.RenameColumns(TextoCartaClean,{{"TextoCarta - Copia", "TextoCarta - Clean"}}),
    /*------Limpiar texto de la carta------*/
    #"Valor reemplazado18" = Table.ReplaceValue(#"Columnas con nombre cambiado2","[{""Texto"":""","",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado19" = Table.ReplaceValue(#"Valor reemplazado18","""},{""Texto"":"""," ",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado20" = Table.ReplaceValue(#"Valor reemplazado19","""}]"," ",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado21" = Table.ReplaceValue(#"Valor reemplazado20","""},,{""Texto"":""","",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado22" = Table.ReplaceValue(#"Valor reemplazado21","MOTIVO","Motivo",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado23" = Table.ReplaceValue(#"Valor reemplazado22","Motivo:","Motivo",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado24" = Table.ReplaceValue(#"Valor reemplazado23","peticion","petición",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    #"Valor reemplazado25" = Table.ReplaceValue(#"Valor reemplazado24","derecho de petición","Derecho de Petición",Replacer.ReplaceText,{"TextoCarta - Clean"}),
    /*------Motivos, Resuestas PQR------*/
    MotivoCarta = Table.AddColumn(#"Valor reemplazado25", "Motivo", each if Text.Contains([#"TextoCarta - Clean"], "MOTIVO: Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "MOTIVO Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo: Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Recurso de Reposición") then "Recurso de Reposición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo: Recurso de Reposición") then "Recurso de Reposición" else if Text.Contains([#"TextoCarta - Clean"], "MOTIVO Recurso de Reposición") then "Recurso de Reposición" else if Text.Contains([#"TextoCarta - Clean"], "MOTIVO: Recurso de Reposición") then "Recurso de Reposición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo: Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "MOTIVO: Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "MOTIVO Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Resolución de Apelación") then "Resolución de Apelación" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Resolución de apelación") then "Resolución de Apelación" else if Text.Contains([#"TextoCarta - Clean"], "Asunto: Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Asunto Derecho de petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Asunto: Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Asunto Derecho de Petición") then "Derecho de Petición" else if Text.Contains([#"TextoCarta - Clean"], "Motivo Solicitud de Silencio") then "Solicitud de Silencio Administrativo" else if Text.Contains([#"TextoCarta - Clean"], "Motivo: Solicitud de Silencio") then "Solicitud de Silencio Administrativo" else "Sin Motivo"),
    /*------Resumen de la carta------*/
    Resumen = Table.AddColumn(MotivoCarta, "Resumen", each Text.AfterDelimiter(Text.BeforeDelimiter([#"TextoCarta - Clean"],"le informamos que"),"En respuesta a su comunicación presentada en donde nos manifiesta"))
in
    Resumen
